import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="relative overflow-hidden">
          <div className="flex flex-col items-center max-w-6xl w-full mx-auto">
            <Navbar />
            <main className="w-full pb-12 px-4">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
